version: '3.9'
services:
  db:
    container_name: mysql_todo
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'todo_db'
      MYSQL_USER: 'todo'
      MYSQL_PASSWORD: 'kN75vZW99qb2MunR'
      MYSQL_ROOT_PASSWORD: 'GGWMkdd9gDmLYMdp'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - './data/mysql:/var/lib/mysql'

  mongo:
    container_name: mongo_todo
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'todo'
      MONGO_INITDB_ROOT_PASSWORD: 'v98YumMqbkN752MunR'
      MONGO_INITDB_DATABASE: 'todo_db'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - './data/mongo/db:/data/db'
      - './data/mongo/mongodb:/home/mongodb'